pipeline {
    agent any
    stages {
        stage("Test") {
            steps {
                script {
                    print "### Test #07"
                    sh "ls -al"
                }
            }
        }
    }
}